# Generated by Django 3.1.7 on 2021-05-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_simple', '0005_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
